import { notFound } from "next/navigation";
import { readData, findStudent } from "@/lib/data";

interface Props {
  params: { id: string };
}

export function generateStaticParams() {
  const data = readData();
  return data.students.map((s) => ({ id: String(s.id) }));
}

export default function ReportPage({ params }: Props) {
  const data = readData();
  const student = findStudent(data, Number(params.id));
  if (!student) notFound();

  const status = student.at_risk ? "AT RISK" : "ON TRACK";

  return (
    <div
      style={{
        background: "#000",
        minHeight: "100vh",
        padding: 16,
        fontFamily: "Times New Roman, Times, serif",
      }}
    >
      <div
        style={{
          maxWidth: 760,
          margin: "0 auto",
          background: "#fff",
          color: "#000",
          border: "1px solid #000",
          padding: 28,
        }}
      >
        <header style={{ borderBottom: "3px double #000", paddingBottom: 12 }}>
          <p style={{ margin: 0, textAlign: "right" }}>
            AXEL REPORT &mdash; NAAC SEMESTER SYSTEM
          </p>
          <h1 style={{ margin: "6px 0 0", fontFamily: "Arial Black, Arial, sans-serif", fontSize: 22 }}>
            Student Performance Report
          </h1>
          <p style={{ margin: "4px 0 0" }}>
            Student: <strong>{student.name}</strong> (ID {student.id}) &middot;{" "}
            Study group {student.group} &middot; Status:{" "}
            <strong>{status}</strong>
          </p>
        </header>

        <section style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 1, background: "#000", marginTop: 16 }}>
          {[
            ["Overall GPA", student.gpa.toFixed(2)],
            ["Attendance", `${student.attendance.toFixed(1)}%`],
            ["Predicted GPA", student.predicted_gpa.toFixed(2)],
            ["Sem 1 GPA", student.gpa_sem1.toFixed(2)],
            ["Sem 2 GPA", student.gpa_sem2.toFixed(2)],
            ["GPA trend", `${student.gpa_delta > 0 ? "+" : ""}${student.gpa_delta.toFixed(2)}`],
          ].map(([label, value]) => (
            <div key={label} style={{ background: "#fff", padding: 10 }}>
              <p className="caps" style={{ margin: 0, fontSize: 10 }}>{label}</p>
              <p style={{ margin: 0, fontSize: 20, fontWeight: 700 }}>{value}</p>
            </div>
          ))}
        </section>

        <section style={{ marginTop: 18 }}>
          <h2 style={{ fontSize: 15, borderBottom: "1px solid #000", paddingBottom: 4 }}>
            Recommended books
          </h2>
          <ul>
            {student.recommended_books.map((b) => (
              <li key={b}>{b}</li>
            ))}
          </ul>
        </section>

        <section style={{ marginTop: 18 }}>
          <h2 style={{ fontSize: 15, borderBottom: "1px solid #000", paddingBottom: 4 }}>
            Weakest subjects
          </h2>
          <ul>
            {student.weakest_subjects.length ? (
              student.weakest_subjects.map((s) => <li key={s}>{s}</li>)
            ) : (
              <li>None detected</li>
            )}
          </ul>
        </section>

        <section style={{ marginTop: 18 }}>
          <h2 style={{ fontSize: 15, borderBottom: "1px solid #000", paddingBottom: 4 }}>
            Professor recommendations
          </h2>
          <ul>
            {student.professors.length ? (
              student.professors.map((p) => <li key={p}>{p}</li>)
            ) : (
              <li>No referrals needed</li>
            )}
          </ul>
        </section>

        <section style={{ marginTop: 18 }}>
          <h2 style={{ fontSize: 15, borderBottom: "1px solid #000", paddingBottom: 4 }}>
            Study group
          </h2>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
            <thead>
              <tr style={{ textAlign: "left" }}>
                <th style={{ borderBottom: "1px solid #000" }}>ID</th>
                <th style={{ borderBottom: "1px solid #000" }}>Student</th>
                <th style={{ borderBottom: "1px solid #000" }}>GPA</th>
              </tr>
            </thead>
            <tbody>
              {student.study_group.map((m) => (
                <tr key={m.id}>
                  <td style={{ padding: "4px 0" }}>{m.id}</td>
                  <td style={{ padding: "4px 0" }}>{m.name}</td>
                  <td style={{ padding: "4px 0" }}>{m.gpa.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <footer style={{ marginTop: 28, borderTop: "1px solid #000", paddingTop: 10, fontSize: 12, display: "flex", justifyContent: "space-between" }}>
          <span>Generated by AXEL Student Performance System</span>
          <a href={`/student/${student.id}`}>&larr; Back to dashboard</a>
        </footer>
      </div>
    </div>
  );
}
